---
# vars file for mac

# Needed to clone private Github repositories
github_token: "{{ lookup('env','GITHUB_TOKEN') }}"

# Tap list
taps: [
  'argoproj/tap',
  'k14s/tap',
]

# Program lists
languages: [
  'go',
  'node',
  'python3',
  'ruby',
]

dev_tools: [
  'duti',
  'hey',
  'http-server',
  'jq',
  'poetry',
  'protobuf',
]

lab_tools: [
  'awscli',
  'bash-completion',
  'consul',
  'docker-completion',
  'docker-compose-completion',
  'hostess',
  'lastpass-cli',
  'packer',
  'packer-completion',
  'pip-completion',
  'pulumi',
  'terraform',
  'vault',
]

kube_tools: [
  'argoproj/tap/argocd',
  'helm',
  'kapp',
  'krew',
  'kubectl',
  'kubectx',
  'minikube',
]

casks: ['multipass']

# Python packages
py_packages: [
  'kapitan',
  'passlib',
  'pyvmomi',
  'git+https://github.com/vmware/vsphere-automation-sdk-python.git',
]

# Personal repositories
personal_repositories: [
  'glab',
  'vssh',
]

# GilmanLab repositories
glab_repositories: [
  'deploy',
  'dev',
  'images'
]

# Misc scripts which need to be in ~/bin
scripts: ['cluster']